version: '3'

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/hao/server-data/code-server/config:/config
      - /home/hao:/home/coder/project
    ports:
      - 9003:8443
    restart: unless-stopped
    networks:
      - home-proxy-network