version: '3.5'

include:
  - ./homepage/docker-compose.yml
  - ./portainer/docker-compose.yml
  - ./freshrss/docker-compose.yml
  - ./adguardhome/docker-compose.yml
  - ./code-server/docker-compose.yml

  networks:
    home-proxy-network:
      name: home_server_virtual_network