version: '3'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 8080:3000
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/hao/server-data/homepage/config:/app/config # Make sure your local config directory exists
      - /home/hao/server-data/homepage/config/icons:/app/public/icons # for self hosted icons
      - /home/hao/server-data/homepage/config/images:/app/public/images # for self hosted images
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped
    networks:
      - home-proxy-network