version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      # DNS
      - 5353:53
        # # DHCP server
        # - 67:67/udp
        # - 68:68/tcp
        # - 68:68/udp
        # # HTTPS/DNS-over-HTTPS
        # - 443:443/tcp
        # # DNS-over-TLS
        # - 853:853/tcp
        # # DNS-over-QUIC
        # - 784:784/udp
        # # DNSCrypt
        # - 5443:5443/tcp
        # - 5443:5443/udp
      # WebUI
      - 9002:3000/tcp
    volumes:
      - ${APP_ROOT}/adguardhome/work:/opt/adguardhome/work
      - ${APP_ROOT}/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - home-proxy-network
