version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_ROOT}/portainer/data:/data
    restart: unless-stopped
    networks:
      - home-proxy-network
