version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/hao/server-data/portainer/data:/data